SELECT 
    e.EMPLOYEE_ID,
    e.HIRE_DATE,
    j.JOB_TITLE,
    d.DEPARTMENT_NAME,
    e.SALARY,
    e.COMMISSION_PCT,
    j.MIN_SALARY,
    j.MAX_SALARY
        
FROM HR.EMPLOYEES e

LEFT JOIN HR.JOBS j 
    ON e.JOB_ID = j.JOB_ID

LEFT JOIN HR.JOB_HISTORY h
    ON e.EMPLOYEE_ID = h.EMPLOYEE_ID

LEFT JOIN HR.DEPARTMENTS d
    ON e.DEPARTMENT_ID = d.DEPARTMENT_ID

WHERE h.END_DATE IS NULL

ORDER BY e.EMPLOYEE_ID ASC