SELECT 
    e.EMPLOYEE_ID,
    e.HIRE_DATE,
    TO_CHAR(e.HIRE_DATE, 'YYYY') AS YEAR_HIRE_DATE,
    TO_CHAR(e.HIRE_DATE, 'MM') AS MONTH_HIRE_DATE,
    TRUNC(MONTHS_BETWEEN(SYSDATE, e.HIRE_DATE)) AS CONTRATATION_IN_MONTHS,
    h.START_DATE,
    h.END_DATE,
    j.JOB_TITLE,
    d.DEPARTMENT_NAME,
    d.MANAGER_ID,
    e.SALARY,
    e.COMMISSION_PCT,
    j.MIN_SALARY,
    j.MAX_SALARY,
    d.LOCATION_ID
    
FROM HR.EMPLOYEES e

LEFT JOIN HR.JOBS j 
    ON e.JOB_ID = j.JOB_ID

LEFT JOIN HR.JOB_HISTORY h
    ON e.EMPLOYEE_ID = h.EMPLOYEE_ID

LEFT JOIN HR.DEPARTMENTS d
    ON e.DEPARTMENT_ID = d.DEPARTMENT_ID

WHERE h.START_DATE IS NULL AND h.END_DATE IS NULL

ORDER BY e.EMPLOYEE_ID ASC