SELECT 
    e.EMPLOYEE_ID,
    e.SALARY,
    e.COMMISSION_PCT,
    l.STREET_ADDRESS,
    l.POSTAL_CODE,
    l.CITY,
    l.STATE_PROVINCE,
    c.COUNTRY_NAME,
    r.REGION_NAME
    
FROM HR.EMPLOYEES e

LEFT JOIN HR.JOB_HISTORY h
    ON e.EMPLOYEE_ID = h.EMPLOYEE_ID

LEFT JOIN HR.DEPARTMENTS d
    ON e.DEPARTMENT_ID = d.DEPARTMENT_ID

LEFT JOIN HR.LOCATIONS l
    ON d.LOCATION_ID = l.LOCATION_ID

LEFT JOIN HR.COUNTRIES c
    ON l.COUNTRY_ID = c.COUNTRY_ID

LEFT JOIN HR.REGIONS r
    ON c.REGION_ID = r.REGION_ID

WHERE h.END_DATE IS NULL

ORDER BY e.EMPLOYEE_ID ASC